export const OPTIONS = [
  'architect',
  'back-end developer lead',
  'back-end developer mid',
  'business analyst',
  'devops',
  'devops automation architect',
  'devops cloud architect',
  'devops lead',
  'devops release manager',
  'devops site reliability engineer',
  'devops system administrator',
  'documentation specialist',
  'engineering manager',
  'front-end developer lead',
  'front-end developer mid',
  'product owner',
  'project manager',
  'qa',
  'qa lead',
  'scrum master',
  'security engineer',
  'software quality engineer',
  'ux/ui leader',
  'ux/ui'
]
